### ISSUE TITLE
Update all check and fixes to match newest DISA RHEL 7 STIG

### ISSUE THREAD

**Issue by samcornwell** [djhaynes/inspec-profile-disa_stig-el7#15]
Additionally update the inspec code to resolve any discrepancies introduced by an updated check or fix text.

Red Hat Enterprise Linux 7 STIG - Ver 1, Rel 4
1/26/2018
https://iase.disa.mil/stigs/os/unix-linux/Pages/red-hat.aspx

**Comment by ejaronne** [comment]
I am working this going from Release 1 to Release 4 using a branch from dev called "dev_to_RHEL7r4" located at: https://github.com/ejaronne/inspec-profile-disa_stig-el7/tree/dev_to_RHEL7r4/controls

**Comment by samcornwell** [comment]
Fixed by #36
